version: '3.8'

volumes:
  postgres:

services:
  user_service_db:
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    restart: always
    build: .
    ports:
      - '8090:8090'
    depends_on:
      - user_service_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://user_service_db:5432/user_service_db'
      JAVA_OPTS: 'Xmx512m'