-- changeset nerkebaev:1
create table users
(
    id       bigint generated by default as identity
        primary key,
    email    varchar(255) not null
        unique,
    password varchar(255) not null,
    role     varchar(255) not null
        constraint users_role_check
            check ((role)::text = ANY
        ((ARRAY ['ROLE_USER'::character varying, 'ROLE_MODERATOR'::character varying, 'ROLE_ADMIN'::character varying])::text[])),
    username varchar(255) not null
        unique
);

alter table users
    owner to postgres;